[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "11111111111111111111111111111111"
pda_messenger = "8KPzbM2Cwn4Yjak7QYAEH9wyoQh86NcBicaLuzPaejdw"

[programs.devnet]
hello_anchor = "11111111111111111111111111111111"
pda_messenger = "8KPzbM2Cwn4Yjak7QYAEH9wyoQh86NcBicaLuzPaejdw"

[programs.mainnet]
hello_anchor = "11111111111111111111111111111111"
pda_messenger = "8KPzbM2Cwn4Yjak7QYAEH9wyoQh86NcBicaLuzPaejdw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
